import { HugeiconsIcon } from "@hugeicons/react";
import {
  AlarmClockIcon,
  Apple01Icon,
  Bicycle01Icon,
  Book02Icon,
  BookOpen01Icon,
  Brain01Icon,
  BulbIcon,
  Calendar01Icon,
  Camera01Icon,
  CheckmarkCircle02Icon,
  CleanIcon,
  Clock01Icon,
  Coffee01Icon,
  Coins01Icon,
  DropletIcon,
  Dumbbell01Icon,
  Fire02Icon,
  FlowerIcon,
  FootballIcon,
  GlassWaterIcon,
  GuitarIcon,
  HealtcareIcon,
  HeartIcon,
  Home01Icon,
  Idea01Icon,
  Leaf01Icon,
  Medal01Icon,
  Money01Icon,
  Moon02Icon,
  MusicNote01Icon,
  PaintBoardIcon,
  PencilEdit01Icon,
  PiggyBankIcon,
  PillIcon,
  Plant02Icon,
  RecycleIcon,
  Restaurant01Icon,
  SleepingIcon,
  SmartPhone01Icon,
  Sun01Icon,
  Sun03Icon,
  Target01Icon,
  TeaIcon,
  TranslateIcon,
  TreeIcon,
  ViewIcon,
  WalkingIcon,
  Wallet01Icon,
  WashingMachineIcon,
  WorkoutRunIcon,
  Yoga01Icon,
} from "@hugeicons/core-free-icons";

type IconType = React.ComponentProps<typeof HugeiconsIcon>["icon"];

// Conjunto curado de ícones para hábitos (chave estável guardada no hábito +
// usada para renderizar). Também alimenta o icon picker.
export const HABIT_ICONS: { key: string; icon: IconType }[] = [
  { key: "circle", icon: CheckmarkCircle02Icon },
  { key: "droplet", icon: DropletIcon },
  { key: "glass-water", icon: GlassWaterIcon },
  { key: "coffee", icon: Coffee01Icon },
  { key: "tea", icon: TeaIcon },
  { key: "apple", icon: Apple01Icon },
  { key: "restaurant", icon: Restaurant01Icon },
  { key: "pill", icon: PillIcon },
  { key: "healthcare", icon: HealtcareIcon },
  { key: "heart", icon: HeartIcon },
  { key: "run", icon: WorkoutRunIcon },
  { key: "walking", icon: WalkingIcon },
  { key: "dumbbell", icon: Dumbbell01Icon },
  { key: "yoga", icon: Yoga01Icon },
  { key: "bicycle", icon: Bicycle01Icon },
  { key: "football", icon: FootballIcon },
  { key: "moon", icon: Moon02Icon },
  { key: "sleeping", icon: SleepingIcon },
  { key: "sun", icon: Sun01Icon },
  { key: "sunrise", icon: Sun03Icon },
  { key: "brain", icon: Brain01Icon },
  { key: "idea", icon: Idea01Icon },
  { key: "bulb", icon: BulbIcon },
  { key: "target", icon: Target01Icon },
  { key: "book", icon: Book02Icon },
  { key: "book-open", icon: BookOpen01Icon },
  { key: "pencil", icon: PencilEdit01Icon },
  { key: "translate", icon: TranslateIcon },
  { key: "paint", icon: PaintBoardIcon },
  { key: "guitar", icon: GuitarIcon },
  { key: "music", icon: MusicNote01Icon },
  { key: "camera", icon: Camera01Icon },
  { key: "phone", icon: SmartPhone01Icon },
  { key: "home", icon: Home01Icon },
  { key: "clean", icon: CleanIcon },
  { key: "washing", icon: WashingMachineIcon },
  { key: "recycle", icon: RecycleIcon },
  { key: "leaf", icon: Leaf01Icon },
  { key: "plant", icon: Plant02Icon },
  { key: "flower", icon: FlowerIcon },
  { key: "tree", icon: TreeIcon },
  { key: "money", icon: Money01Icon },
  { key: "wallet", icon: Wallet01Icon },
  { key: "coins", icon: Coins01Icon },
  { key: "piggybank", icon: PiggyBankIcon },
  { key: "fire", icon: Fire02Icon },
  { key: "clock", icon: Clock01Icon },
  { key: "alarm", icon: AlarmClockIcon },
  { key: "calendar", icon: Calendar01Icon },
  { key: "eye", icon: ViewIcon },
  { key: "medal", icon: Medal01Icon },
];

const ICON_BY_KEY = new Map(HABIT_ICONS.map((i) => [i.key, i.icon]));

export function habitIcon(key: string): IconType {
  return ICON_BY_KEY.get(key) ?? CheckmarkCircle02Icon;
}
